---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robots
  labels:
    role: robots
spec:
  replicas: 5
  selector:
    matchLabels:
      app: robots
      role: robots
      tier: rust
  template:
    metadata:
      labels:
        app: robots
        role: robots
        tier: rust
    spec:
      containers:
        - name: robots
          image: smrangel/robot-ini:v0.001
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
