apiVersion: v1
kind: Service
metadata: 
    name: robots3
spec:
    selector: 
         app: robots3
    type: NodePort
    ports: 
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30005
      protocol: TCP