apiVersion: v1
kind: Service
metadata: 
    name: robots2
spec:
    selector: 
         app: robots2
    type: NodePort
    ports: 
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30004
      protocol: TCP