#!/bin/bash
arch_null(){ #argumentos  //archivo_de_salida //linea_de_trabajo_en_el_archivo_de_salida
if [[ 0 -eq $(awk '{print $1}' <<< $(wc -c $1)) ]]; then
        if [[ -z $(grep -n $2  $1 | sed -e 's/:/ /g' | awk '{print $1}') ]]; then 
		echo $2 > $1
        	sed -i -e s/$2//g $1    ### eliminar archivo anterior
                pwd
                echo "nuevo"
                echo $2
                #grep $2 $1
        fi
        if [[ '' != $(grep -n $2 $1 | sed -e 's/:/ /g' | awk '{print $1}') ]]; then
                echo "la linea ya estaba"
        fi

  else
  if [[ 0 -ne $(awk '{print $1}' <<< $(wc -c $1)) ]]; then
         if [[ -z $(grep -n $2 $1 | sed -e 's/:/ /g' | awk '{print $1}') ]]; then
                echo $2 >> $1
                echo "viejo"
                echo $2
                pwd
         fi
         if [[ '' != $(grep -n $2 $1 | sed -e 's/:/ /g' | awk '{print $1}') ]]; then
                echo "la linea ya estaba"
         fi
  fi
  fi
}
while IFS='' read -r line; do
        cd ~/robots
        vb=$(find . -path ./*$line)
        cd ./gpg
        pss=$(./2BEeAFkM $3)
        echo 'pss: ' $pss
        echo '$vb: ' $vb
        dfg=$(sed s/.gpg//g <<< $vb)
        echo 'dfg: ' $dfg
        cd ../
        gpg --output $dfg --batch --yes --pinentry-mode loopback --passphrase $pss -d $vb #2>/dev/null
        cd ./gpg/$1
        echo "vb: "$vb
        pwd
        arch_null "dec" $line
done < ~/robots/gpg/$1/$2
